; sbcl --load project-2.lisp --load project-2-test.lisp --eval '(run-tests)'

(defmacro test-case (stx result)
  `(let ((actual ,stx))
     (if (equal actual ,result)
       (format t "PASS")
       (format t "FAIL"))
     (format t " ~a == ~a, got ~a~%" (quote ,stx) ,result actual)))

(defun test-set-eq (a b) (test-case (set-difference a b) NIL))

(defun run-tests ()
  ; EXP->NNF
  (test-case (exp->nnf '(not (not a))) 'a)
  (test-case (exp->nnf '(not (and a b))) '(OR (NOT A) (NOT B)))
  (test-case (exp->nnf '(not (or a (not b)))) '(AND (NOT A) B))
  (test-case (exp->nnf '(not (:iff a b))) '(OR (AND A (NOT B)) (AND B (NOT A))))
  (test-case (exp->nnf '(:xor a b)) '(and (or a b) (or (not a) (not b))))
  (test-case (exp->nnf '(:iff a b)) '(and (or (not a) b) (or (not b) a)))
  (test-case (exp->nnf '(:implies A B)) '(or (not A) B))

  ; EXP->CNF
  ;Base cases/powerpoint cases
  (test-case (exp->cnf '(:iff A B)) '(and  (or (NOT B) A)(or (NOT A) B))) 
  (test-case (exp->cnf '(:implies A B)) '(and (or (not A) B)))
  (test-case (exp->cnf '(:xor A B)) '(and (or (not A) (not B)) (or A B)))
  (test-case (exp->cnf '(not (not a))) '(and (or A)))
  (test-case (exp->cnf '(not (and a b))) '(AND (OR (NOT A) (NOT B))))
  (test-case (exp->cnf '(or a (and b g))) '(and (or G A) (or B A)))
  (test-case (exp->nnf '(:implies (not (or a b)) c)) '(or (or a b) c))
  (test-case (exp->CNF '(:xor (not (or a b)) (and a c))) '(and (or (not b) a) (or (not a) c) (or (not b)) c))

  ; DPLL
  (test-case (dpll (cnf-maxterms '(and (or a)))) t)
  (test-case (dpll (cnf-maxterms '(and (or a) (or (not a))))) nil)
  (test-case (dpll (cnf-maxterms '(and (or a b) (or (not a) b)))) t)
  (test-case (dpll (cnf-maxterms (exp->cnf '(and a (not a))))) nil)
  (test-case (dpll (cnf-maxterms (exp->cnf '(or a (not a))))) t)
  (test-case (dpll (cnf-maxterms '(and (or a (not a))))) t)
  (test-case (dpll (cnf-maxterms '(and (or a b) (or (not a) (not b))))) t)
  (test-case (dpll (cnf-maxterms '(and (or a (not a)) (or b (not b) c)))) t)
  (test-case (dpll (cnf-maxterms '(and (or a a a b b b c c c (not a) (not a) (not b) d)))) t)
  (test-case (dpll (cnf-maxterms '(and (or a b c d (not a) (not a) a)))) t)
  (test-case (dpll (cnf-maxterms '(and (or a) (or (not a))))) nil)
  (test-case (dpll (cnf-maxterms '(and (or a) (or b) (or (not b)) (or c d e f g)))) nil)

  ;test sat-p
  (test-case (sat-p '(and (or a) (or b) (or c d))) t)
  (test-case (sat-p '(:implies a b)) t)
  (test-case (sat-p '(and (:implies a b) (or (not b)))) t)
  (test-case (sat-p '(and (:implies a b) (or (not b)) (or a))) nil)
  (test-case (sat-p '(:iff a b)) t)
  (test-case (sat-p '(and (:iff a b) (or (not a)))) t)
  (test-case (sat-p '(and (and a b) (or b c))) t)
  (test-case (sat-p '(and (and a b c) (not a))) nil)
  (test-case (sat-p '(or (not a) a)) t)
  (test-case (sat-p '(or (and a b) (and (not a) b) (and a (not b)))) t)
  (test-case (sat-p '(and (or a b) (or a b) (or a b))) t)
  (test-case (sat-p '(and (:implies a b) (:iff a b) a (not b))) nil)
  (test-case (sat-p '(and (:implies a (not b)) (:iff a b))) t)
  (test-case (sat-p '(and (:implies a (not b)) (:iff (not a) b) a b)) nil)
  (test-case (sat-p '(and (and a b) (and (not a) (not b)))) nil)
  (test-case (sat-p '(or (and a b) (and (not a) (not b)))) t)
  (test-case (sat-p '(:implies (or a b) (not b))) t)
  (test-case (sat-p '(and (:implies (or a b) (not b)) b)) nil)
  (test-case (sat-p '(and (:iff (and a b) (or (not a) b)) (not a))) nil)
  (test-case (sat-p '(:iff a (not a))) nil)
  (test-case (sat-p '(:iff (and a b) (not (and a b)))) nil)

  (multiple-value-bind (a b) (sat-p 
'(and ( or (NOT noop_clear_peg2-1)    clear_peg2-0 )
( or (NOT noop_clear_peg3-1)   clear_peg3-0 )
( or (NOT noop_smaller_disk1_disk2-1)    smaller_disk1_disk2-0 )
( or (NOT move-disk_disk1_disk2_peg2-1)    clear_peg2-0 )
( or (NOT move-disk_disk1_disk2_peg2-1)    clear_disk1-0 )
( or (NOT move-disk_disk1_disk2_peg2-1)    on_disk1_disk2-0 )
( or (NOT move-disk_disk1_disk2_peg2-1)   smaller_disk1_peg2-0 )
( or (NOT move-disk_disk1_disk2_peg3-1)   clear_peg3-0 )
( or (NOT move-disk_disk1_disk2_peg3-1)   clear_disk1-0 )
( or (NOT move-disk_disk1_disk2_peg3-1)   on_disk1_disk2-0 )
( or (NOT move-disk_disk1_disk2_peg3-1)   smaller_disk1_peg3-0 )
( or (NOT noop_smaller_disk1_peg2-1)    smaller_disk1_peg2-0 )
( or (NOT noop_smaller_disk1_peg3-1)    smaller_disk1_peg3-0 )
( or (NOT noop_on_disk1_disk2-1)    on_disk1_disk2-0 )
( or (NOT noop_on_disk2_peg1-1)    on_disk2_peg1-0 )
( or (NOT noop_clear_disk1-1)    clear_disk1-0 )
( or (NOT noop_smaller_disk2_peg2-1)    smaller_disk2_peg2-0 )
( or (NOT noop_smaller_disk2_peg3-1)    smaller_disk2_peg3-0 )
( or (NOT noop_clear_peg3-2)    clear_peg3-1 )
( or (NOT noop_smaller_disk1_disk2-2 )   smaller_disk1_disk2-1 )
( or (NOT move-disk_disk1_peg3_disk2-2)   clear_disk2-1 )
( or (NOT move-disk_disk1_peg3_disk2-2 )  clear_disk1-1 )
( or (NOT move-disk_disk1_peg3_disk2-2 )  on_disk1_peg3-1 )
( or (NOT move-disk_disk1_peg3_disk2-2 )  smaller_disk1_disk2-1 )
( or (NOT move-disk_disk1_disk2_peg2-2 )  clear_peg2-1 )
( or (NOT move-disk_disk1_disk2_peg2-2 )  clear_disk1-1 )
( or (NOT move-disk_disk1_disk2_peg2-2 )   on_disk1_disk2-1 )
( or (NOT move-disk_disk1_disk2_peg2-2 )  smaller_disk1_peg2-1 )
( or (NOT move-disk_disk1_disk2_peg3-2 )  clear_peg3-1 )
( or (NOT move-disk_disk1_disk2_peg3-2 )  clear_disk1-1 )
( or (NOT move-disk_disk1_disk2_peg3-2 )  on_disk1_disk2-1 )
( or (NOT move-disk_disk1_disk2_peg3-2 )  smaller_disk1_peg3-1 )
( or (NOT move-disk_disk2_peg1_peg2-2)    clear_peg2-1 )
( or (NOT move-disk_disk2_peg1_peg2-2 )   clear_disk2-1 )
( or (NOT move-disk_disk2_peg1_peg2-2 )   on_disk2_peg1-1 )
( or (NOT move-disk_disk2_peg1_peg2-2 )   smaller_disk2_peg2-1 )
( or (NOT move-disk_disk1_peg3_peg2-2 )   clear_peg2-1 )
( or (NOT move-disk_disk1_peg3_peg2-2 )   clear_disk1-1 )
( or (NOT move-disk_disk1_peg3_peg2-2 )   on_disk1_peg3-1 )
( or (NOT move-disk_disk1_peg3_peg2-2 )   smaller_disk1_peg2-1 )
( or (NOT move-disk_disk2_peg1_peg3-2 )   clear_peg3-1 )
( or (NOT move-disk_disk2_peg1_peg3-2 )   clear_disk2-1 )
( or (NOT move-disk_disk2_peg1_peg3-2 )   on_disk2_peg1-1 )
( or (NOT move-disk_disk2_peg1_peg3-2 )   smaller_disk2_peg3-1 )
( or (NOT noop_on_disk1_disk2-2)    on_disk1_disk2-1 )
( or (NOT move-disk_disk1_peg2_disk2-2)    clear_disk2-1 )
( or (NOT move-disk_disk1_peg2_disk2-2)    clear_disk1-1 )
( or (NOT move-disk_disk1_peg2_disk2-2)    on_disk1_peg2-1 )
( or (NOT move-disk_disk1_peg2_disk2-2)    smaller_disk1_disk2-1 )
( or (NOT noop_on_disk2_peg1-2)    on_disk2_peg1-1 )
( or (NOT noop_clear_disk1-2)    clear_disk1-1 )
( or (NOT noop_clear_disk2-2)    clear_disk2-1 )
( or (NOT move-disk_disk1_peg2_peg3-2)    clear_peg3-1 )
( or (NOT move-disk_disk1_peg2_peg3-2)    clear_disk1-1 )
( or (NOT move-disk_disk1_peg2_peg3-2)    on_disk1_peg2-1 )
( or (NOT move-disk_disk1_peg2_peg3-2)    smaller_disk1_peg3-1 )
( or (NOT noop_on_disk1_peg2-2)    on_disk1_peg2-1 )
( or (NOT noop_on_disk1_peg3-2)    on_disk1_peg3-1 )
( or (NOT noop_smaller_disk2_peg3-2)    smaller_disk2_peg3-1 )
( or (NOT move-disk_disk2_peg2_peg3-3)    clear_peg3-2 )
( or (NOT move-disk_disk2_peg2_peg3-3)    clear_disk2-2 )
( or (NOT move-disk_disk2_peg2_peg3-3)    on_disk2_peg2-2 )
( or (NOT move-disk_disk2_peg2_peg3-3)    smaller_disk2_peg3-2 )
( or (NOT move-disk_disk1_peg3_disk2-3)    clear_disk2-2 )
( or (NOT move-disk_disk1_peg3_disk2-3)    clear_disk1-2 )
( or (NOT move-disk_disk1_peg3_disk2-3)    on_disk1_peg3-2 )
( or (NOT move-disk_disk1_peg3_disk2-3)    smaller_disk1_disk2-2 )
( or (NOT move-disk_disk2_peg1_peg3-3)    clear_peg3-2 )
( or (NOT move-disk_disk2_peg1_peg3-3)    clear_disk2-2 )
( or (NOT move-disk_disk2_peg1_peg3-3)    on_disk2_peg1-2 )
( or (NOT move-disk_disk2_peg1_peg3-3)    smaller_disk2_peg3-2 )
( or (NOT noop_on_disk1_disk2-3)    on_disk1_disk2-2 )
( or (NOT move-disk_disk1_peg2_disk2-3 )   clear_disk2-2 )
( or (NOT move-disk_disk1_peg2_disk2-3 )   clear_disk1-2 )
( or (NOT move-disk_disk1_peg2_disk2-3 )   on_disk1_peg2-2 )
( or (NOT move-disk_disk1_peg2_disk2-3)    smaller_disk1_disk2-2 )
( or (NOT noop_on_disk2_peg3-3 )   on_disk2_peg3-2 )
( or (NOT clear_peg3-1)     noop_clear_peg3-1  )
( or (NOT smaller_disk2_peg2-1)     noop_smaller_disk2_peg2-1  )
( or (NOT smaller_disk2_peg3-1)     noop_smaller_disk2_peg3-1  )
( or (NOT on_disk1_peg2-1)     move-disk_disk1_disk2_peg2-1  )
( or (NOT on_disk1_peg3-1)     move-disk_disk1_disk2_peg3-1  )
( or (NOT clear_disk1-1)     noop_clear_disk1-1  )
( or (NOT clear_disk2-1)     move-disk_disk1_disk2_peg2-1  move-disk_disk1_disk2_peg3-1 )
( or (NOT smaller_disk1_disk2-1)     noop_smaller_disk1_disk2-1  )
( or (NOT smaller_disk1_peg2-1)     noop_smaller_disk1_peg2-1  )
( or (NOT smaller_disk1_peg3-1)     noop_smaller_disk1_peg3-1  )
( or (NOT on_disk1_disk2-1)     noop_on_disk1_disk2-1  )
( or (NOT on_disk2_peg1-1)     noop_on_disk2_peg1-1  )
( or (NOT clear_peg2-1)     noop_clear_peg2-1  )
( or (NOT noop_clear_peg2-1)    (NOT move-disk_disk1_disk2_peg2-1 ))
( or (NOT noop_clear_peg3-1)    (NOT move-disk_disk1_disk2_peg3-1 ))
( or (NOT move-disk_disk1_disk2_peg2-1)    (NOT move-disk_disk1_disk2_peg3-1 ))
( or (NOT move-disk_disk1_disk2_peg2-1)    (NOT noop_on_disk1_disk2-1 ))
( or (NOT move-disk_disk1_disk2_peg3-1)    (NOT noop_on_disk1_disk2-1 ))
( or (NOT on_disk2_peg3-2)    move-disk_disk2_peg1_peg3-2  )
( or (NOT clear_peg3-2 )    noop_clear_peg3-2  move-disk_disk1_peg3_disk2-2  move-disk_disk1_peg3_peg2-2  )
( or (NOT smaller_disk2_peg3-2)     noop_smaller_disk2_peg3-2  )
( or (NOT on_disk1_peg2-2)     noop_on_disk1_peg2-2  move-disk_disk1_peg3_peg2-2  move-disk_disk1_disk2_peg2-2 ) 
( or (NOT on_disk1_peg3-2)     noop_on_disk1_peg3-2  move-disk_disk1_peg2_peg3-2  move-disk_disk1_disk2_peg3-2 ) 
( or (NOT clear_disk1-2 )    noop_clear_disk1-2  )
( or (NOT smaller_disk1_disk2-2)     noop_smaller_disk1_disk2-2  )
( or (NOT clear_disk2-2)     noop_clear_disk2-2  move-disk_disk1_disk2_peg2-2  move-disk_disk1_disk2_peg3-2  )
( or (NOT on_disk1_disk2-2)     noop_on_disk1_disk2-2  move-disk_disk1_peg2_disk2-2  move-disk_disk1_peg3_disk2-2  )
( or (NOT on_disk2_peg1-2)     noop_on_disk2_peg1-2 )
( or (NOT on_disk2_peg2-2)     move-disk_disk2_peg1_peg2-2  )
( or (NOT noop_clear_peg3-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT noop_clear_peg3-2)    (NOT move-disk_disk2_peg1_peg3-2 ))
( or (NOT noop_clear_peg3-2)    (NOT move-disk_disk1_disk2_peg3-2 ))
( or (NOT noop_clear_peg3-2)    (NOT move-disk_disk1_peg3_peg2-2 ))
( or (NOT noop_clear_peg3-2)    (NOT move-disk_disk1_peg3_disk2-2 ))
( or (NOT noop_clear_peg3-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk1_peg3_peg2-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk1_disk2_peg3-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk1_disk2_peg2-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk2_peg1_peg2-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT noop_clear_disk2-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT move-disk_disk2_peg1_peg3-2 ))
( or (NOT move-disk_disk1_peg3_disk2-2)    (NOT noop_on_disk1_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT move-disk_disk1_disk2_peg3-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT noop_on_disk1_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT move-disk_disk1_peg3_peg2-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT move-disk_disk2_peg1_peg3-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT move-disk_disk2_peg1_peg2-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT noop_clear_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg2-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT noop_on_disk1_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)   (NOT move-disk_disk2_peg1_peg3-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)   (NOT move-disk_disk2_peg1_peg2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT noop_clear_disk2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT move-disk_disk1_peg3_peg2-2 ))
( or (NOT move-disk_disk1_disk2_peg3-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT move-disk_disk2_peg1_peg3-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT noop_on_disk2_peg1-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT move-disk_disk1_peg3_peg2-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT noop_on_disk1_disk2-2 ))
( or (NOT move-disk_disk2_peg1_peg2-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk1_peg3_peg2-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT move-disk_disk1_peg3_peg2-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk1_peg3_peg2-2)    (NOT move-disk_disk2_peg1_peg3-2 ))
( or (NOT move-disk_disk1_peg3_peg2-2)    (NOT noop_on_disk1_disk2-2 ))
( or (NOT move-disk_disk1_peg3_peg2-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk1_peg3_peg2-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk2_peg1_peg3-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk2_peg1_peg3-2)    (NOT noop_on_disk2_peg1-2 ))
( or (NOT move-disk_disk2_peg1_peg3-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk2_peg1_peg3-2)    (NOT noop_on_disk1_disk2-2 ))
( or (NOT move-disk_disk2_peg1_peg3-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT noop_on_disk1_disk2-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT noop_on_disk1_disk2-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT noop_on_disk1_disk2-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT noop_on_disk1_disk2-2)    (NOT noop_clear_disk2-2 ))
( or (NOT noop_on_disk1_disk2-2)    (NOT move-disk_disk1_peg2_disk2-2 ))
( or (NOT move-disk_disk1_peg2_disk2-2)    (NOT move-disk_disk1_peg2_peg3-2 ))
( or (NOT move-disk_disk1_peg2_disk2-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk1_peg2_disk2-2)    (NOT noop_clear_disk2-2 ))
( or (NOT move-disk_disk1_peg2_disk2-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT move-disk_disk1_peg2_peg3-2)    (NOT noop_on_disk1_peg2-2 ))
( or (NOT move-disk_disk1_peg2_peg3-2)    (NOT noop_on_disk1_peg3-2 ))
( or (NOT noop_on_disk1_peg2-2)    (NOT noop_on_disk1_peg3-2 ))
( or noop_on_disk2_peg3-3  move-disk_disk2_peg1_peg3-3  move-disk_disk2_peg2_peg3-3  )
( or noop_on_disk1_disk2-3  move-disk_disk1_peg2_disk2-3  move-disk_disk1_peg3_disk2-3  )
( or (NOT move-disk_disk2_peg2_peg3-3 )   (NOT move-disk_disk1_peg2_disk2-3 ))
( or (NOT move-disk_disk2_peg2_peg3-3 )   (NOT move-disk_disk1_peg3_disk2-3 ))
( or (NOT move-disk_disk2_peg2_peg3-3 )   (NOT move-disk_disk2_peg1_peg3-3 ))
( or (NOT move-disk_disk2_peg2_peg3-3 )   (NOT noop_on_disk1_disk2-3 ))
( or (NOT move-disk_disk2_peg2_peg3-3 )   (NOT noop_on_disk2_peg3-3 ))
( or (NOT move-disk_disk1_peg3_disk2-3)    (NOT noop_on_disk2_peg3-3 ))
( or (NOT move-disk_disk1_peg3_disk2-3 )   (NOT move-disk_disk2_peg1_peg3-3 ))
( or (NOT move-disk_disk1_peg3_disk2-3 )   (NOT move-disk_disk1_peg2_disk2-3 ))
( or (NOT move-disk_disk1_peg3_disk2-3)    (NOT noop_on_disk1_disk2-3 ))
( or (NOT move-disk_disk2_peg1_peg3-3)    (NOT move-disk_disk1_peg2_disk2-3 ))
( or (NOT move-disk_disk2_peg1_peg3-3)    (NOT noop_on_disk1_disk2-3 ))
( or (NOT move-disk_disk2_peg1_peg3-3)    (NOT noop_on_disk2_peg3-3 ))
( or (NOT noop_on_disk1_disk2-3 )   (NOT noop_on_disk2_peg3-3 ))
( or (NOT noop_on_disk1_disk2-3)    (NOT move-disk_disk1_peg2_disk2-3 ))
 clear_peg3-0
 smaller_disk2_peg2-0
 smaller_disk2_peg3-0
 clear_disk1-0
 smaller_disk1_disk2-0
 smaller_disk1_peg2-0
 smaller_disk1_peg3-0
 on_disk1_disk2-0
 on_disk2_peg1-0
 clear_peg2-0
 on_disk2_peg3-3
 on_disk1_disk2-3
))
    (print a)
    (print b))
)
